main:
  appName: "your app name"
  host: "127.0.0.1"
  port: 8000
  
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  databaseName: "your database name"
  
redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  
authCode:
  accessKeyID: "your accessKeyID in alibaba cloud"
  accessKeySecret: "your accessKeySecret in alibaba cloud"
  signName: "阿里云短信测试"
  templateCode: "SMS_154950909"
  
log:
  logPath: "your log path"
  
kafka:
  messageMode: "channel"# 消息模式 channel or kafka
  hostPort: "127.0.0.1:9092" # "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094" 多个kafka服务器
  chatTopic: "chat_message"
  partition: 0 # kafka partition
  timeout: 1 # 单位秒
  
staticSrc:
  staticAvatarPath: "./static/avatars"
  staticFilePath: "./static/files"